package scanner

import (
	"fmt"

	"github.com/batiazinga/hdl/iohdl/internal/token"
)

// Error is a positioned error generated by the scanner
// if the source has invalid encoding.
type Error struct {
	p token.Position
}

func (e Error) Error() string {
	return fmt.Sprintf("%s: invalid encoding", e.p)
}

// Position returns the position of the error in the source.
func (e Error) Position() token.Position { return e.p }
