package scanner

import "fmt"

// Error is a positioned error generated by the scanner
// if the source has invalid encoding.
type Error struct {
	p Position
}

func (e Error) Error() string {
	return fmt.Sprintf("%s: invalid encoding", e.p)
}

// Position returns the position of the error in the source.
func (e Error) Position() Position { return e.p }
